import { useMetamask, useAddress, useContract } from '@thirdweb-dev/react'
import Head from 'next/head'
import Navbar from './components/Navbar';
import Hero from './components/Hero';
export default function Home() {
    const address = useAddress();
    const metamaskWallet = useMetamask();
    const contract = useContract(process.env.CONTRACT_ADDRESS, 'edition-drop');
  return (
    <>
      <Head>
        <title>NFT Ticketing - Decentralized Ticketing System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black">
        <Navbar/>
        <Hero />
      </main>
    </>
  );
}
